apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m2r95ki69-go
  janus-idp.io/tekton: m2r95ki69-go
  backstage.io/kubernetes-id: m2r95ki69-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m2r95ki69-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
